# MinIO credentials for Nessie
apiVersion: v1
kind: Secret
metadata:
  name: nessie-minio-secret
type: Opaque
stringData:
  awsAccessKeyId: YOUR_ACCESS_KEY_ID
  awsSecretAccessKey: YOUR_SECRET_ACCESS_KEY

---
# Postgres credentials for Nessie
apiVersion: v1
kind: Secret
metadata:
  name: nessie-version-store-secret
type: Opaque
stringData:
  username: YOUR_POSTGRES_USERNAME
  password: YOUR_POSTGRES_PASSWORD
