# Bitnami OpenLDAP Secret
apiVersion: v1
kind: Secret
metadata:
  name: openldap-config
type: Opaque
stringData:
  LDAP_ADMIN_PASSWORD: YOUR_OPENLDAP_ADMIN_PASSWORD
  LDAP_ADMIN_USERNAME: YOUR_OPENLDAP_ADMIN_USERNAME
  LDAP_ROOT: dc=example,dc=org
  LDAP_ADMIN_DN: cn=YOUR_OPENLDAP_ADMIN_USERNAME,dc=example,dc=org

---

# dnknth/ldap-ui secret
apiVersion: v1
kind: Secret
metadata:
  name: openldap-ui-config
type: Opaque
stringData:
  LDAP_URL: ldap://openldap:1389/
  BASE_DN: dc=example,dc=org
  BIND_PASSWORD: YOUR_OPENLDAP_ADMIN_PASSWORD
  BIND_DN: cn=YOUR_OPENLDAP_ADMIN_USERNAME,dc=example,dc=org
  LOGIN_ATTR: cn
  USE_TLS: ""
  INSECURE_TLS: ""
  SCHEMA_DN: cn=subSchema